exclude: ['README.md']
timezone: US/Pacific

markdown:         kramdown
highlighter:      rouge

permalink:        pretty

sass:
  sass_dir: /assets/_sass
  style: :compressed

# optionally remove smart quotes
#kramdown:
#    smart_quotes: ["apos", "apos", "quot", "quot"]

# Setup
title:            'MICRO 51 Website'
description:      'MICRO 2018 Conference'
baseurl:          'https://www.microarch.org/micro51'


#paginate:         5
#assets:           /public/
#imageurl:         /public/images/
#fileurl:          /public/files/
#cssurl:           /public/css/

# About/contact
author:
  name:            'Hidetsugu Irie'
  url:              http://www.mtl.t.u-tokyo.ac.jp/~irie/en/
  email:           irie@mtl.t.u-tokyo.ac.jp
  github:          https://github.com/hide-irie
 
# Custom vars
version:           1.0.0

