exclude: ['README.md']
timezone: US/Pacific

markdown:         kramdown
highlighter:      rouge

permalink:        pretty

sass:
  sass_dir: /assets/_sass
  style: :compressed

# optionally remove smart quotes
#kramdown:
#    smart_quotes: ["apos", "apos", "quot", "quot"]

# Setup
title:            'MICRO 50 Website'
description:      'MICRO 2017 Conference'
baseurl:          'https://www.microarch.org/micro50'


#paginate:         5
#assets:           /public/
#imageurl:         /public/images/
#fileurl:          /public/files/
#cssurl:           /public/css/

# About/contact
author:
  name:            'Arrvindh Shriraman'
  url:             http://www.cs.sfu.ca/~ashriram/
  email:           ashriram@cs.sfu.ca
  github:          https://github.com/ashriram
 
# Custom vars
version:           1.0.0

